#!/bin/bash

clear

. ./vars

echo "Stopping steamcache..."

docker stop $STEAMCACHE >/dev/null

echo "Stopping lancache..."

docker stop $LANCACHE >/dev/null

echo "Stopping steamcache-dns..."

docker stop $DNS >/dev/null

echo "Stopping tmux session..."

tmux kill-session -t steamcache >/dev/null
tmux kill-session -t htop >/dev/null
tmux kill-session -t iftop-lan >/dev/null

echo "All services stopped."
