#!/bin/bash

clear

echo "  ____        _ _   _        _    _   _ "
echo " / ___|  __ _| | |_| |      / \  | \ | |"
echo " \___ \ / _ \`| | __| |     / _ \ |  \| |"
echo "  ___) | (_| | | |_| |___ / ___ \| |\  |"
echo " |____/ \__,_|_|\__|_____/_/   \_\_| \_|"
echo "                                        "
echo "          @Pips801 & @Glitchvid         "
echo "                                        "

. ./vars

echo "Stopping steamcache..."

docker stop $STEAMCACHE >/dev/null

echo "Stopping lancache..."

docker stop $LANCACHE >/dev/null

echo "Stopping steamcache-dns..."

docker stop $DNS >/dev/null

echo "Stopping tmux session..."

tmux kill-session -t steamcache >/dev/null
tmux kill-session -t htop >/dev/null
tmux kill-session -t iftop-lan >/dev/null

echo "All services stopped."
